name: learn-github-actions
run-name: 02 - Maven basics steps
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      - name: Set up Java
        uses: actions/setup-java@v2

        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build with maven
        run: mvn clean test package install

